# Used to illustrate deployment environments
name: Deployment environments workflow
run-name: Deploy to ${{ github.event.inputs.environment }}
env:
  MY_ENV_VAR: "default" # this can be overriden by defining a variable within the GitHub environments section

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        type: 'choice'
        required: true
        default: 'staging'
        options:
          - 'staging'
          - 'production'

jobs:
  echo-welcome:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Echo welcome message
        run: echo "Welcome to the deployment environments workflow. The environment variable is:" ${{ env.MY_ENV_VAR }}