# Used to illustrate deployment environments
name: Deployment environments workflow
run-name: Deploy to ${{ inputs.environment }}
env:
    MY_ENV_VAR: ${{ vars.MY_ENV_VAR || 'DEFAULT' }}

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Lower environment to deploy to'
        type: 'choice'
        required: true
        default: 'staging'
        options:
          - 'staging'
          - 'dev'

jobs:
  deploy-lower-environment:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: deploy-lower
        run: echo "Welcome to the deployment environments workflow. The environment variable is:" ${{ vars.MY_ENV_VAR || 'DEFAULT' }}

  deploy-production:
    needs: deploy-lower-environment
    runs-on: ubuntu-latest
    environment: production
    steps:
        - name: deploy-prod
          run: echo "Welcome to the deployment environments workflow. The environment variable is:" ${{ vars.MY_ENV_VAR || 'DEFAULT' }}